mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
ccflags-y += -I$(dir $(mkfile_path))/../../../common
obj-y		:= falcon1024.o
falcon1024-y	:= codec.o common.o fft.o fpr.o keygen.o pqclean.o rng.o sign.o vrfy.o main_module.o #../../../common/fips202.o
