mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
ccflags-y += -I$(dir $(mkfile_path))/../../../common
obj-y		:= sphincs_shake_128s_simple.o
sphincs_shake_128s_simple-y	:= address.o context_shake.o fors.o hash_shake.o merkle.o sign.o sign.o thash_shake_simple.o utils.o utilsx1.o wots.o wotsx1.o main_module.o #../../../common/fips202.o
